version: '3.8'

services:
  # Teacher Portal
  teacher:
    build:
      context: .
      dockerfile: apps/teacher-portal/Dockerfile
    container_name: lms-teacher
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: ''
      NEXT_TELEMETRY_DISABLED: '1'
      NODE_ENV: production
    ports:
      - '192.168.24.23:4001:3000'

  # Student Portal
  student:
    build:
      context: .
      dockerfile: apps/student-portal/Dockerfile
    container_name: lms-student
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: ''
      NEXT_TELEMETRY_DISABLED: '1'
      NODE_ENV: production
    ports:
      - '192.168.24.23:4002:3000'
